baseURL = "https://tignioj.github.io/"

# Change the default theme to be use when building the site with Hugo
theme = "Doit"

# website title
title = "Codee的博客"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"


ignorefiles = [ ".obsidian/.*","_template/*"]


[outputs]
home = ["HTML", "RSS", "JSON"]

